[[main]]
    name = "Search"
    identifier = "search"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 8
    url = "/search"

[[main]]
    name = "Projects"
    identifier = "projects"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 10
    url = "/projects"

[[main]]
    name = "Schedule"
    identifier = "schedule"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 20
#    parent = "sessions"
    url = "/schedule"

[[main]]
    name = "Members"
    identifier = "members"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 30
    url = "/membership/"


#### Past EVENTS ####



[[main]]
    name = "Past Summits"
    identifier = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 40

[[main]]
    name = "Jan 2024"
    identifier = "event-jan-2024"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 25
    url = "/sessions/2024/mini-summits/jan/"

[[main]]
    name = "Oct 2023"
    identifier = "event-oct-2023"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 26
    url = "/sessions/2023/mini-summits/oct/"

[[main]]
    name = "Jun 2023"
    identifier = "event-jun-2023"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 27
    url = "/sessions/2023/mini-summits/jun/"

[[main]]
    name = "Apr 2023"
    identifier = "event-apr-2023"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 28
    url = "/sessions/2023/mini-summits/apr/"

[[main]]
    name = "Feb 2023"
    identifier = "event-feb-2023"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 29
    url = "/sessions/2023/mini-summits/feb/"

[[main]]
    name = "Dec 2022"
    identifier = "event-dec-2022"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 30
    url = "/sessions/2022/mini-summits/dec/"


[[main]]
    name = "Sep 2022"
    identifier = "event-sep-2022"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 31
    url = "/sessions/2022/mini-summits/sep/"

[[main]]
    name = "Jul 2022"
    identifier = "event-jul-2022"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 32
    url = "/sessions/2022/mini-summits/jul/"


[[main]]
    name = "May 2022"
    identifier = "event-may-2022"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 34
    url = "/sessions/2022/mini-summits/may/"

[[main]]
    name = "Mar 2022"
    identifier = "event-mar-2022"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 35
    url = "/sessions/2022/mini-summits/mar/"


[[main]]
    name = "Jan 2022"
    identifier = "event-jan-2022"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 36
    url = "/sessions/2022/mini-summits/jan/"

[[main]]
    name = "Nov 2021"
    identifier = "event-nov-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 37
    url = "/sessions/2021/mini-summits/nov/"

[[main]]
    name = "Sep 2021"
    identifier = "event-sep-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 38
    url = "/sessions/2021/mini-summits/sep/"

[[main]]
    name = "Jun 2021"
    identifier = "event-jun-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 39
    url = "/sessions/2021/mini-summits/jun/"

[[main]]
    name = "May 2021"
    identifier = "event-may-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 40
    url = "/sessions/2021/mini-summits/may/"

[[main]]
    name = "Apr 2021"
    identifier = "event-apr-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 41
    url = "/sessions/2021/mini-summits/apr/"

[[main]]
    name = "Mar 2021"
    identifier = "event-mar-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 42
    url = "/sessions/2021/mini-summits/mar/"

[[main]]
    name = "Jan 2021"
    identifier = "event-jan-2021"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 43
    url = "/sessions/2021/mini-summits/jan/"

[[main]]
    name = "Dec 2020"
    identifier = "event-dec-2020"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 44
    url = "/sessions/2020/mini-summits/dec/"

[[main]]
    name = "Nov 2020"
    identifier = "event-nov-2020"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 45
    url = "/sessions/2020/mini-summits/nov/"

[[main]]
    name = "Oct 2020"
    identifier = "event-ot-2020"
    parent = "past-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 46
    url = "/sessions/2020/mini-summits/oct/"


#### Future EVENTS ####


[[main]]
    name = "Future Summits"
    identifier = "future-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 60

[[main]]
    name = "Jun 2024"
    identifier = "event-jun-2024"
    parent = "future-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 24
    url = "/sessions/2024/mini-summits/jun/"

[[main]]
    name = "Sep 2024"
    identifier = "event-sep-2024"
    parent = "future-summits"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 25
    url = "/sessions/2024/mini-summits/sep/"




[[main]]
    name = "About"
    identifier = "about"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 71
    url = "/about/"

[[main]]
    name = "The Summit"
    identifier = "about-the-summit"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 75
    parent = "about"
    url = "/about/"
[[main]]
    name = "Faq"
    identifier = "faq"
    pre = "<i class='fa fa-road'></i>&nbsp;"
    weight = 80
    parent = "about"
    url = "/faq/"
[[main]]
    name = "Sponsors"
    identifier = "sponsors"
    weight = 90
    pre = "<i class='fa fa-road'></i>&nbsp;"
    url = "/sponsors/"
    parent = "about"


### OLD menus

# Main menu
#[[main]]
#    name = "Reactions"
#    identifier = "reactions"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 1
#    url = "/Reactions"
#[[main]]
#    name = "Outcomes"
#    identifier = "outcomes"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 2
#    url = "/outcomes/"
#[[main]]
#    name = "Video"
#    identifier = "Video"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 8
#    url = "/video/"
#[[main]]
#    name = "Merchandise"
#    identifier = "Merchandise"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 9
#    url = "https://pre-summit-training-sessions.heysummit.com/merchandise-3/"

#    name = "Photo Gallery"
#    identifier = "PhotoGallery"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 8
#    url = "/photo-gallery/"
#[[main]]
#    name = "Sessions"
#    identifier = "sessions"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 3
#    url = "/working-sessions/"

#[[main]]
#    name = "Trainings"
#    identifier = "training"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 4
#    url = "/training/"

#[[main]]
#    name = "Topics"
#    identifier = "topics"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 6
##    parent = "sessions"
#    url = "/topics/"

#[[main]]
#    name = "Working Sessions"
#    identifier = "working-sessions"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 5
#    parent = "sessions"
#    url = "/working-sessions/"
#[[main]]
#    name = "User Sessions"
#    identifier = "user-sessions"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
###    weight = 16
#    parent = "sessions"
#    url = "/user-sessions/"
#[[main]]
#    name = "Teams"
#    identifier = "teams"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 17
#    parent = "sessions"
#    url = "/teams"
#[[main]]
#    name = "Product Sessions"
#    identifier = "product-sessions"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 18
#    parent = "sessions"
#    url = "/product-sessions"
#[[main]]
#    name = "Participants"
#    identifier = "participants"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 7
#    url = "/participant/"
#    parent = "about"
#[[main]]
#    name = "Onsite Participants"
#    identifier = "onsite-participants"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 13
#    parent = "participants"
#    url = "/participant/"
#[[main]]
#    name = "Remote Participants"
#    identifier = "Remote-participants"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 14
#    parent = "participants"
#    url = "/participant-remote/"

#[[main]]
#    name = "Venue"
#    identifier = "venue"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 21
#    parent = "about"
#    url = "/venue/"

#[[main]]
#    name = "Partners"
#    identifier = "partners"
#    pre = "<i class='fa fa-road'></i>&nbsp;"
#    weight = 21
#    parent = "about"
#    url = "/partners"
#[[main]]
#    name = "Tickets"
#    identifier = "tickets"
#    pre = "<i class='fa fa-ticket'></i>&nbsp;"
#    weight = 12
#    url = "/tickets/"


# Top bar social links menu
[[topbar]]
    weight = 1
    name = "Twitter"
    url = "https://twitter.com/opensecsummit"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/OpenSecuritySummit/oss2021"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[topbar]]
    weight = 3
    name = "Slack"
    url = "https://join.slack.com/t/os-summit/shared_invite/zt-eptzb479-POZlYeYI1vaNNZzVatF2ag"
    pre = "<i class='fa fa-2x fa-slack'></i>"

[[topbar]]
    weight = 4
    name = "Youtube"
    url = "https://www.youtube.com/channel/UCyse9b_2JLJUxKMLgSpOL-Q/"
    pre = "<i class='fa fa-2x fa-youtube'></i>"

